kind: Secret
apiVersion: v1
data:
  .dockerconfigjson: >-
    {{ .Values.githubpackagesecret }}
metadata:
  name: {{ include "bcdc-smk.fullname" . }}-pullsecret
  labels:
    {{- include "bcdc-smk.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

type: kubernetes.io/dockerconfigjson

