# NOT USED!
# keeping this in the project as it is a start for how the secrets associated with a 
# template might be defined.
# 
# - Tried to pre-define the secrets associated with a service account 
# - hope was that the service accounts would use these secrets and not
# - automatically create their own.
# - This was not the case
# - SA got access to the secrets but didn't use them, still created
#   the default 2 image pull and 2 access secrets
#

kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Secret
    data:
      .dockerconfigjson: >-
        ${OC_IMAGE_STREAM_TOKEN}
    type: kubernetes.io/dockerconfigjson
    metadata:
      name: ${PREFIX}-dockercfg
  - apiVersion: v1
    data:
      ca.crt: >-
        ${OC_ACCESS_CACRT}
      service-ca.crt: >-
        ${OC_ACCESS_SERVICE_CRT}
      token: >-
        ${OC_ACCESS_TOKEN}
    kind: Secret
    metadata:
      annotations:
        kubernetes.io/created-by: openshift.io/create-dockercfg-secrets
      name: ${PREFIX}-token
      namespace: ${DEPLOY_NAMESPACE}
    type: kubernetes.io/service-account-token
  
parameters:
- name: DEPLOY_NAMESPACE
  displayName: prefix
  value: dbc-kirk-dev
- name: PREFIX
  displayName: prefix
  value: gha-deploy-sa
- name: OC_IMAGE_STREAM_TOKEN
  displayName: oc-docker-token
  required: true
  description: secret for accessing openshift image stream, not used
- name: OC_ACCESS_CACRT
  displayName: access-crt
  required: true
- name: OC_ACCESS_SERVICE_CRT
  displayName: access-service-crt
  required: true
- name: OC_ACCESS_TOKEN
  displayName: access-token
  required: true
