# This is a basic workflow to help you get started with Actions

name: BUILD Package

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
# -------- DEBUGGING --------
# on:
#   pull_request:
#     branches: ['master']

on:
  push:
    branches:    
      - dev

jobs:
  # This workflow contains a single job called "build"
  buildjob:
    name: Build BCDC-SMK container image
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      id: checkout
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        # -------- DEBUGGING --------
        # 
        #ref: v2
        fetch-depth: 0
    - name: calculateImageTag
      id: calculateImageTag
      run: echo ::set-output name=DOCKER_VERSION_TAG::$(date +%Y%m%d-%H%M)
      outputs:
        containerTag:
          description: 'calculate the tag id'
          value: ${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}


    - name: testing the output
      id: testoutput
      run: echo tag version is ${{ steps.calculateImageTag.outputs.DOCKER_VERSION_TAG }}
    
    # -------- DEBUGGING --------
    # - name: Create the docker image
    #   uses: docker/build-push-action@v1
    #   with:
    #     registry: docker.pkg.github.com
    #     username: $GITHUB_ACTOR
    #     password: ${{ secrets.GITHUB_TOKEN  }}
    #     repository: bcgov/bcdc-smk/bcdc-smk
    #     tag_with_ref: true
    #     tag_with_sha: true
    #     add_git_labels: true
    #     tags: ${{ env.DOCKER_VERSION_TAG }}
    #     push: true

  # -------- DEBUGGING --------
  # outputs syntax works apparently in GHA but not using ACT.
  deployDev:
    name: Deploy the image to delivery environment
    needs: buildjob
    runs-on: ubuntu-18.04
    # reference tag using: ${{ needs.buildjob.outputs.containerTag}}
    steps:
    - run: echo image tag is ${{ needs.buildjob.outputs.containerTag.DOCKER_VERSION_TAG}} 



