
name: "DEV Deploy"

on:
  workflow_run:
    workflows: ["BUILDPackage", "build"]
    types: 
      - completed

jobs:
  deploydev:
    defaults:
      run:
        shell: bash
    # RETRIEVE IMAGE TAGS
    runs-on: ubuntu-18.04
    steps:
    - name: Retrieve image tag
      id: retrieveimagetag
      run: |
        export

        #cat < $GITHUB_EVENT_PATH


        artifactsUrl="${GITHUB_API_URL}/repos/${GITHUB_REPOSITORY}/actions/artifacts"
        echo artifacts url is $artifactsUrl
        artifactDlUrl=$(curl --location --request GET $artifactsUrl \
        --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq '.artifacts[0].archive_download_url') | tr -d '"'
        echo  artifact download link is $artifactDlUrl
        curl --location --request GET $artifactDlUrl --header 'Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' --data-raw '' --output arty.zip
        echo downloaded artifact arty.zip
        unzip arty.zip
        IMAGE_TAG=$(cat docker_image_tag.txt)
        rm docker_image_tag.txt
        rm arty.zip
        
        echo "::set-env name=DOCKER_VERSION_TAG::$IMAGE_TAG"

        echo "::set-env name=DOCKER_VERSION_TAG::$IMAGE_TAG"
        echo testing set of env var: $DOCKER_VERSION_TAG
    # LOGGING INTO OC
    - name: OpenShift Action
      id: GHAOpenshiftTest
      uses: redhat-developer/openshift-actions@v1.1
      with:
        version: '3.11.232'
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        parameters: '{"apitoken": "${{ secrets.API_TOKEN }}", "acceptUntrustedCerts": "true"}'
        cmd: 'version'
     
    # PERFORM THE DEPLOY
    - name: deploy dev
      id: deploydev
      run: |
        oc version
        oc whoami
        oc status
        whereis oc

        DEPLOY_NAMESPACE=dbc-kirk-dev

        # ------------------- extract the object names from the template -------------------
        ROUTENAME=$(oc process -f ./openshift/deployTemplate.yaml -p ENV=dev -p IMAGE_LABEL=$DOCKER_VERSION_TAG | jq '.items[] | select(.kind=="Route") | .metadata.name')
        DEPLOYNAME=$(oc process -f ./openshift/deployTemplate.yaml -p ENV=dev -p IMAGE_LABEL=$DOCKER_VERSION_TAG  | jq '.items[] | select(.kind=="DeploymentConfig") | .metadata.name')
        SERVICENAME=$(oc process -f ./openshift/deployTemplate.yaml -p ENV=dev -p IMAGE_LABEL=$DOCKER_VERSION_TAG  | jq '.items[] | select(.kind=="Service") | .metadata.name')
        
        # ------------------- delete objects if they exist -------------------
        EXISTINGDEPLOYNAME=$(oc get deploymentconfigs -n $DEPLOY_NAMESPACE -o json | jq  '.items[] | select(.metadata.name=='$DEPLOYNAME') | .metadata.name')
        if [ ! -z "$EXISTINGDEPLOYNAME" ]
        then
          oc delete deploymentconfig $EXISTINGDEPLOYNAME
        fi
        EXISTINGROUTENAME=$(oc get routes -n $DEPLOY_NAMESPACE -o json | jq  '.items[] | select(.metadata.name=='$ROUTENAME') | .metadata.name')
        if [ ! -z "$EXISTINGROUTENAME" ]
        then
          oc delete route $EXISTINGROUTENAME
        fi
        EXISTINGSERVICENAME=$(oc get deploymentconfigs -n $DEPLOY_NAMESPACE -o json | jq  '.items[] | select(.metadata.name=='$SERVICENAME') | .metadata.name')
        if [ ! -z "$EXISTINGSERVICENAME" ]
        then
          oc delete route $EXISTINGSERVICENAME
        fi

        # ------------------- NOW CREATE THE OBJECTS -------------------
        oc process -f ./openshift/deployTemplate.yaml -p ENV=dev -p IMAGE_LABEL=$DOCKER_VERSION_TAG -p DEPLOY_NAMESPACE=$DEPLOY_NAMESPACE | oc create -n $DEPLOY_NAMESPACE -f - 

        echo route name is $ROUTENAME
        ROUTEPATH=$(oc get routes -n dbc-kirk-tools -o json | jq  '.items[] | select(.metadata.name=='$ROUTENAME') | .spec.host' | tr -d '"')
        echo route is 'https://'$ROUTEPATH

        # ------------------- SET THE ROUTEPATH ouptut
        run: echo ::set-output name=ROUTEPATH::$(ROUTEPATH)

    - name: Update issue
      id: updateissue
      run: |
        # add a comment for the issue associated with the pr that includes the 
        # path to the dev deploy of the app
        #
        # possibly also do a 'request' for reviews to someone defined in an env 
        # var somewhere
        # change the status of the pull request to "review required"
        echo "not implemented yet"
  